language: python
python:
  - 2.6
  - 2.7
  - 3.3
virtualenv:
  system_site_packages: true
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update
  - sudo apt-get install -qq gfortran
  # numpy is installed anyway, even on py!=2.7 where system site-packages are never available. keep it here for completeness
  - sudo apt-get install -qq python-numpy
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install wheel
  ### wheel building/upload start
  - cd /tmp
  - mkdir wheelhouse-build
  - sudo apt-get build-dep --ignore-missing -qq -y python-scipy python-suds python-lxml python-sqlalchemy python-m2crypto
  - pip wheel ${WHEEL_BUILD_ARGS} numpy
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build numpy
  - pip wheel ${WHEEL_BUILD_ARGS} scipy
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build scipy
  - pip wheel ${WHEEL_BUILD_ARGS} matplotlib lxml sqlalchemy m2crypto
  - pip wheel ${WHEEL_BUILD_ARGS} $SUDS
  - git clone https://${GH_TOKEN}@github.com/obspy/wheelhouse.git /tmp/wheelhouse
  - mv -n /tmp/wheelhouse-build/* /tmp/wheelhouse/
  - cd /tmp/wheelhouse/
  - git config --local user.email "travis@travis-ci.org"
  - git config --local user.name "travis-ci"
  - git add *
  - git commit -m "Uploading new wheels"
  - git push --quiet origin master || ( git pull --rebase && git push --quiet origin master)
  - exit 0
  ### wheel building/upload end
  - cd /tmp
  - wget -q -O - 'https://github.com/obspy/wheelhouse/archive/master.tar.gz' | tar -xzf -
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install -qq python-dev python-scipy python-suds python-lxml python-sqlalchemy python-m2crypto; else pip install --use-wheel --no-index --find-links=/tmp/wheelhouse-master scipy suds lxml sqlalchemy m2crypto; fi
  - pip install https://github.com/yarikoptic/coveralls-python/archive/master.zip
  - pip install geographiclib
  - pip install --use-wheel --no-index --find-links=/tmp/wheelhouse-master matplotlib
  - pip install --use-mirrors flake8
  - pip freeze
install:
  - git remote add obspy git://github.com/obspy/obspy.git
  - git fetch obspy --tags
  - git fetch origin --tags
  - DEPTH=300; while [ "$(git describe 2> /dev/null)" == "" ]; do DEPTH=$(($DEPTH+200)); git fetch origin --depth=$DEPTH --quiet; done # continue fetching more older commits until git describe is able to reach the last tagged version
  - git status
  - pip install --no-deps --use-mirrors .
  - git status
env:
  global:
    secure: JiBG/vFGw/23q6Y/Sbel35EtqLSl+ehuKBGjrLJtUZFBFxRnbcZvqgDXjC+UpyoPhECMfin/boxvT0nG2p0n3x5Gtp2RyN2ue+U2G5c0ECxe+MTDntBYn2lC6quoIh568uj+gcdLc4Dq2Px9aM0cfQSEBd4TO+ENMgg4MRnEMg0=
    - WHEEL_BUILD_ARGS='-vvv --use-mirrors --allow-all-external --wheel-dir=/tmp/wheelhouse-build'
    - SUDS=`if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '3' ]]; then echo 'suds-jurko'; else echo 'suds'; fi`
script:
  # We change directories to make sure that python won't find the copy
  # of obspy in the source directory, see 
  # https://github.com/numpy/numpy/blob/master/.travis.yml#L44
  - mkdir empty
  - cd empty
  - MODULELIST=`python -c "from obspy.core.util import DEFAULT_MODULES as MODULES; print 'obspy.' + ',obspy.'.join(MODULES)"`
  - coverage run --source=$MODULELIST -m obspy.core.scripts.runtests -n travis-ci -r --keep-images
after_success:
  - coveralls
notifications:
    email: false
# Upload any potentially produced diffs and produced images to imgur after a test failure.
after_failure:
  - cd
  - wget "http://imgur.com/tools/imgurbash.sh"
  - for FILE in `find . -regex '.*/tests/images/testrun/.*png' | sort`; do echo $FILE; bash imgurbash.sh $FILE; done
