language: python
python:
  - 2.6
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update
  - sudo apt-get install -qq gfortran
  # numpy is installed anyway, even on py!=2.7 where system site-packages are never available. keep it here for completeness
  - sudo apt-get install -qq python-numpy
  - git clone --depth=1 git://github.com/obspy/wheelhouse /tmp/obspy-wheelhouse
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install wheel
  ### wheel building/upload start
  - cd /tmp
  - mkdir wheelhouse-build
  - sudo apt-get build-dep --ignore-missing -qq -y python-scipy python-suds python-lxml python-sqlalchemy python-m2crypto
  - pip wheel -v --use-mirrors --wheel-dir=/tmp/wheelhouse-build numpy scipy matplotlib lxml suds sqlalchemy m2crypto
  - git clone https://${GH_TOKEN}@github.com/obspy/wheelhouse.git /tmp/wheelhouse
  - mv -n /tmp/wheelhouse-build/* /tmp/wheelhouse/
  - cd /tmp/wheelhouse/
  - git config --local user.email "travis@travis-ci.org"
  - git config --local user.name "travis-ci"
  - git add *
  - git commit -m "Uploading new wheels"
  - git push origin master || ( git pull --rebase && git push origin master)
  ### wheel building/upload end
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install -qq python-dev python-scipy python-suds python-lxml python-sqlalchemy python-m2crypto; else pip install --use-wheel --no-index --find-links=/tmp/obspy-wheelhouse scipy suds lxml sqlalchemy m2crypto; fi
  - pip install https://github.com/yarikoptic/coveralls-python/archive/master.zip
  - pip install geographiclib
  - pip install --use-wheel --no-index --find-links=/tmp/obspy-wheelhouse matplotlib
  - pip install --use-mirrors flake8
  - pip freeze
install:
  - git remote add obspy git://github.com/obspy/obspy.git
  - git fetch obspy --tags
  - git fetch origin --tags
  - DEPTH=300; while [ "$(git describe 2> /dev/null)" == "" ]; do DEPTH=$(($DEPTH+200)); git fetch origin --depth=$DEPTH --quiet; done # continue fetching more older commits until git describe is able to reach the last tagged version
  - git status
  - pip install --no-deps --use-mirrors .
  - git status
env:
  global:
    secure: "d58TRMIt5kivmnRG4np/jyA1jFTo4gXpaW0xLlPaOlTS9W9SoylNZQP21Dy7LbFB7aLtrxKbKY7vwjMnDBRFXaMbZTKoO8YUTDPOvAz61MDjqfGAjnHESd1lSU+0EJU2h1y6AWWD0pJQCWBbAbT9ePkEiSgBNVzbavqHNHJNoHw="
script:
  # We change directories to make sure that python won't find the copy
  # of obspy in the source directory, see 
  # https://github.com/numpy/numpy/blob/master/.travis.yml#L44
  - mkdir empty
  - cd empty
  - MODULELIST=`python -c "from obspy.core.util import DEFAULT_MODULES as MODULES; print 'obspy.' + ',obspy.'.join(MODULES)"`
  - coverage run --source=$MODULELIST -m obspy.core.scripts.runtests -n travis-ci -r --keep-images
after_success:
  - coveralls
notifications:
    email: false
# Upload any potentially produced diffs and produced images to imgur after a test failure.
after_failure:
  - cd
  - wget "http://imgur.com/tools/imgurbash.sh"
  - for FILE in `find . -regex '.*/tests/images/testrun/.*png' | sort`; do echo $FILE; bash imgurbash.sh $FILE; done
