language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update
  - sudo apt-get install -qq gfortran
  - sudo apt-get install -qq libgeos-3.2.2 libgeos-dev libgeos-c1
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install wheel
  - git clone https://${GH_TOKEN}@github.com/obspy/wheelhouse.git /tmp/wheelhouse
  ### wheel building/upload start
  - cd /tmp
  - mkdir wheelhouse-build
  - sudo apt-get build-dep --ignore-missing -qq -y python-scipy python-suds python-lxml python-sqlalchemy python-m2crypto
  - pip wheel ${WHEEL_BUILD_ARGS} numpy
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build numpy
  - pip wheel ${WHEEL_BUILD_ARGS} scipy
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build scipy
  - pip wheel ${WHEEL_BUILD_ARGS} matplotlib lxml sqlalchemy m2crypto six
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build matplotlib
  # build modified basemap package with the large data files stripped (which we dont use in testing anyway)
  # geos link fix is included in basemap master now
  - pip wheel ${WHEEL_BUILD_ARGS} https://github.com/megies/basemap/archive/v1.0.7_geos_link_fix__no_high_res.zip
  - pip wheel ${WHEEL_BUILD_ARGS} suds suds-jurko
  - mv -n /tmp/wheelhouse-build/* /tmp/wheelhouse/
  - cd /tmp/wheelhouse/
  - git config --local user.email "travis@travis-ci.org"
  - git config --local user.name "travis-ci"
  - git add *
  - git pull
  - git diff --exit-code --staged || exit 0  # exit if no staged changes
  - git commit -m "Uploading new wheels"
  - git push --quiet origin master
  ### wheel building/upload end
  - exit 0
install:
  - exit 0
env:
  global:
    - secure: JiBG/vFGw/23q6Y/Sbel35EtqLSl+ehuKBGjrLJtUZFBFxRnbcZvqgDXjC+UpyoPhECMfin/boxvT0nG2p0n3x5Gtp2RyN2ue+U2G5c0ECxe+MTDntBYn2lC6quoIh568uj+gcdLc4Dq2Px9aM0cfQSEBd4TO+ENMgg4MRnEMg0=
    - WHEEL_BUILD_ARGS='-vvv --use-mirrors --use-wheel --find-links=/tmp/wheelhouse --allow-all-external --wheel-dir=/tmp/wheelhouse-build --allow-insecure matplotlib --allow-insecure basemap --allow-unverified basemap'
script:
  - exit 0
notifications:
    email: false
